import Head from "next/head";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Utkarsh575 portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main></main>

      <footer>
        <h1>footer</h1>
      </footer>
    </div>
  );
}
