import {
  Box,
  Text,
  Center,
  Square,
  Circle,
  useColorModeValue,
  useColorMode,
} from "@chakra-ui/react";
import Nav from "../components/Nax";
import Head from "next/head";

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();
  return (
    <div>
      <Head>
        <title>Utkarsh575 portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav />

      <Box
        w="100%"
        h="100vh"
        bgGradient={useColorModeValue(
          "linear(to-r, #F0E7DB, #F0E7DB)",
          "pink.200"
        )}
        pl="5rem"
        pr="5rem"
      >
        <Center>
          {/* mx={{ base: "1rem", sm: "3rem", md: "7rem", lg: "10rem" }}
           */}
          <Box backgroundColor="gray.200" px="2rem" borderRadius="sm">
            <Text
              bgColor="blue.200"
              bgGradient="linear(to-l, #7928CA, #FF0080)"
              bgClip="text"
              fontSize={{ base: "xs", sm: "xl", md: "2xl", lg: "4xl" }}
              fontWeight="extrabold"
            >
              Hello, I'm a CSE Sophomore at SRMIST!
            </Text>
          </Box>
        </Center>
      </Box>
      <footer>
        <h1>footer</h1>
      </footer>
    </div>
  );
}
